language: node_js

node_js:
- '0.12'

before_install:
- npm install --quiet -g gulp jspm typescript tsd
- jspm config registries.github.remote https://github.jspm.io
- jspm config registries.github.auth YjA5MTprcnRnbWszYQ==
- jspm config registries.github.maxRepoSize 0
- jspm config registries.github.handler jspm-github

before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./node_modules/protractor/bin/install_selenium_standalone
- java -jar selenium/selenium-server-standalone-2.45.0.jar -Dwebdriver.chrome.driver=./selenium/chromedriver &
- sleep 3

script:
- gulp check
- gulp compile
- gulp test:e2e

cache:
  directories:
  - ./node_modules
  - ./vendor
  - $HOME/.nvm

sudo: false
